package main

import (
	"log"
	"time"

	"github.com/cilium/ebpf/link"
)

// CODE GENERATION: This directive runs bpf2go when you execute `go generate`
// bpf2go reads kprobe.c and generates:
//   - bpfObjects struct (with ExecCount map and KprobeExecve program)
//   - loadBpfObjects() function
//   - bpf_bpfel.o and bpf_bpfeb.o (compiled eBPF bytecode)
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target amd64,arm64 bpf kprobe.c -- -I../headers

func main() {
	// STEP 1: Load eBPF objects into the kernel
	// bpfObjects{} is generated by bpf2go from kprobe.c
	// It contains: objs.ExecCount (map) and objs.KprobeExecve (program)
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close() // Cleanup: unload program and maps on exit

	log.Println("✅ eBPF program loaded")

	// STEP 2: Attach kprobe to kernel function
	// This makes our eBPF program run every time sys_execve is called
	kp, err := link.Kprobe("sys_execve", objs.KprobeExecve, nil)
	if err != nil {
		log.Fatalf("attaching kprobe: %v", err)
	}
	defer kp.Close() // Cleanup: detach kprobe on exit

	log.Println("✅ Kprobe attached to sys_execve")
	log.Println("Counting execve syscalls. Press Ctrl+C to exit.")

	// STEP 3: Periodically read the counter from the eBPF map
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		var count uint64
		key := uint32(0) // Array index 0 (our only entry)

		// Read from the map: objs.ExecCount comes from C's exec_count
		if err := objs.ExecCount.Lookup(&key, &count); err != nil {
			log.Printf("reading map: %v", err)
			continue
		}
		log.Printf("📊 Executions: %d", count)
	}
}
